# -*- coding: utf-8 -*-
"""special 02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NP4I-67PjGJtnYnse_1WyEDNMYCZa_a5
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

filepath='/content/creditcard.csv'
df=pd.read_csv(filepath)

df.head()

df.tail()

df.shape

df.columns

df.info()

df.describe()

df.dtypes

df.isnull().sum()

df.nunique()

df.sample(5)

